name: florealesa
description: A flower & gift shop app
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0

flutter:
  uses-material-design: true
